version: "3"

services:
  dns:
    build: dns
    ports:
      - 53:53/tcp
      - 53:53/udp
    command: dnsmasq --no-daemon --log-queries

    #  durak:
    #build: durak
    #tty: true
    #ports:
    #  - 10770:10770
    #command: python server.py 0.0.0.0 10770
    #volumes:
    #  - ./durak:/usr/src/app
